author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-CPAN-YACSmoke
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::Spec: 0
  POE: 0.38
version: 0.13
