---
author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-CPAN-YACSmoke
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0
  POE: 0.38
version: 0.17
